# 本地运行的配置文件
[Server]
AppMode = "debug"   # debug 开发环境, release 生产环境
BackPort = ":8765"  # 后台服务端口
FrontPort = ":5678" # 前台服务端口

[JWT]
Secret = "abc123321"
Expire = 24             # 过期时间 (小时)
Issuer = "Mybilibili"

[Mysql]
Host = "127.0.0.1"
Port = "3306"
Config = ""         # 其他配置, 例如时区
Dbname = "Mybilibili"      # 数据库名称
Username = "root"
Password = "a81033120" # 数据库密码
# 日志级别 silent, error, warn, info, 默认 info
LogMode = "error" # silent 相当于关闭日志

[Redis]
DB = 7
Addr = '127.0.0.1:6379'
Password = ''

[Session]
Name = "mysession"
Salt = "salt"
MaxAge = 600       # 秒

[Zap]
Level = "error"            # 日志级别: debug, info, warn, error, dpanic, panic, fatal, 默认 info
Format = "console"         # 输出格式: console, json
Prefix = "[Mybilibili] " # 日志前缀
Directory = "log"          # 存放日志的文件夹
ShowLine = true            # 是否显示哪行调用
LogInConsole = true        # 是否输出到控制台

[Upload]
OssType = "qiniu"             # 控制存储: local、qiniu
Path = "public/uploaded/"      # 本地文件访问路径 (OssType="local" 才生效)
StorePath = "public/uploaded/" # 本地文件上传路径 (OssType="local" 才生效)
# Markdown 目前只支持本地上传 (目前使用前端导出, 该配置无效)
MdPath = "public/markdown/"      # Markdown 访问路径
MdStorePath = "public/markdown/" # Markdown 上传路径

[Qiniu]
ImgPath = "rqgk41m3z.hd-bkt.clouddn.com"          # 外链
Zone = "ZoneHuadong"                             # 存储区域
Bucket = "springcpr"
AccessKey = "Vscjwi_bdJyAhYIyZYHdM8YH-Ywl2psHclWbNPlO"
SecretKey = "1uGNphkF5cCrikltYFMzYEPlShVcX6WTukXe9Zak"
UseHttps = false      # 是否使用 https 加速
UseCdnDomains = false # 上传是否使用 CDN 上传加速

[Code]
Duration = "5" # 验证码有效时间 (分钟)
Length = 6     # 验证码长度

[Email]
Host = "smtp.qq.com"
Port = "587"
User = "498047949@qq.com"
Password = "lhhmqrnowronbjai"
